parameters = 
{'asDORA': True, 
'gamma': 0.3, 
'delta': 0.1, 
'eta': 0.9, 
'HebbBias': 0.5,
'bias_retrieval_analogs': True, 
'use_relative_act': True, 
'run_order': ['cdr', 'selectTokens', 'r', 'wp', 'm', 'p', 'f', 's', 'c'], 
'run_cyles': 5000, 
'write_on_iteration': 100, 
'firingOrderRule': 'random', 
'strategic_mapping': False, 
'ignore_object_semantics': False, 
'ignore_memory_semantics': True, 
'mag_decimal_precision' = 0, 
'dim_list': [], 
'exemplar_memory': False, 
'recent_analog_bias': True, 
'lateral_input_level': 1, 'screen_width': 1200, 
'screen_height': 700, 
'doGUI': True, 
'GUI_update_rate': 5, 
'starting_iteration': 0}